Repository 9oormthon-univ/2025_SEASONTHON_TEAM_13_BE, pull requests merged in 2025-09, with the labels that each got.

#14 feat: kakao oauth login 구현 및 사용자 데이터 조회kao oauth login 구현 및 사용자 데이터 조회
  .github/workflows/aws.yml
  src/main/java/cloud/emusic/emotionmusicapi/controller/LoginController.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/request/LoginRequest.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/KakaoTokenResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/KakaoUserResponse.java
Labels: 💫 Feat

#16 feat: repository 인터페이스 생성
  src/main/java/cloud/emusic/emotionmusicapi/repository/DayTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/EmotionTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/PostEmotionTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/PostRepository.java
Labels: 💫 Feat

#22 feat(login): JWT 토큰 발행 및 유저데이터 저장
  .github/workflows/aws.yml
  build.gradle
  src/main/java/cloud/emusic/emotionmusicapi/config/JwtTokenProvider.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/LoginController.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/User.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/LoginResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/service/UserService.java
Labels: 💫 Feat

#26 chore: 프론트 CORS 허용
  src/main/java/cloud/emusic/emotionmusicapi/config/SecurityConfig.java
Labels: 🔧 Chore

#24 feat: 게시글(Post) 도메인 기능 구현 (등록,조회)
  src/main/java/cloud/emusic/emotionmusicapi/config/JwtAuthenticationFilter.java
  src/main/java/cloud/emusic/emotionmusicapi/config/JwtTokenProvider.java
  src/main/java/cloud/emusic/emotionmusicapi/config/SecurityConfig.java
  src/main/java/cloud/emusic/emotionmusicapi/config/SwaggerConfig.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/LoginController.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/PostController.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/request/EmotionTagResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
Labels: 💫 Feat, 🔨 Refactor

#29 feat: 댓글 기능 구현 및 개발
  src/main/java/cloud/emusic/emotionmusicapi/controller/CommentController.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/Comment.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/request/CommentRequest.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/CommentResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/CommentRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/CommentService.java
Labels: 💫 Feat

#32 feat: 게시글(post) 관련 API 구현
  src/main/java/cloud/emusic/emotionmusicapi/config/SecurityConfig.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/PostController.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/DayTag.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/Post.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/PostEmotionTag.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/request/PostCreateRequest.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/EmotionTagResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/PostCreateResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/PostResponseDto.java
  src/main/java/cloud/emusic/emotionmusicapi/exception/dto/ErrorCode.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/EmotionTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
Labels: 💫 Feat, 🐛 Fix

#44 feat: 게시글 수정,삭제 API 구현
  src/main/java/cloud/emusic/emotionmusicapi/controller/PostController.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/Post.java
  src/main/java/cloud/emusic/emotionmusicapi/exception/dto/ErrorCode.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/CommentRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/LikeRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
Labels: 💫 Feat

#56 feat: 실시간 태그 검색 순위 조회 API 구현
  src/main/java/cloud/emusic/emotionmusicapi/config/SecurityConfig.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/TagController.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/TagRankingResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/TagRankingResponseWrapper.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/DayTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/PostEmotionTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/TagService.java
Labels: 💫 Feat

#58 feat: 감정 기반 노래 추천 기능 API 구현
  .github/workflows/aws.yml
  src/main/java/cloud/emusic/emotionmusicapi/config/SecurityConfig.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/SpotifyController.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/request/EmotionMapper.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/TrackResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/service/SpotifyService.java
Labels: 💫 Feat

#60 feat: 곡 검색 기능 API 구현
  src/main/java/cloud/emusic/emotionmusicapi/controller/SpotifyController.java
  src/main/java/cloud/emusic/emotionmusicapi/service/SpotifyService.java
Labels: 💫 Feat

#63 feat : track_id로 조회이후 데이터 저장 DB 연동
  src/main/java/cloud/emusic/emotionmusicapi/domain/Post.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/Song.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/PostResponseDto.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/TrackResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/exception/dto/ErrorCode.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/SongRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/SpotifyService.java
Labels: 💫 Feat

#68 fix: 좋아요한 게시글 조회 기능중 다른 사람의 게시글의 좋아요 여부 false로 나오는 버그 해결
  src/main/java/cloud/emusic/emotionmusicapi/repository/LikeRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/LikeService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
Labels: 🐛 Fix

#70 feat: 게시글 노래 재생 횟수 증가 API 구현
  src/main/java/cloud/emusic/emotionmusicapi/controller/SpotifyController.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/Song.java
  src/main/java/cloud/emusic/emotionmusicapi/service/SpotifyService.java
Labels: 💫 Feat

#76 feat: 로그인 유저가 작성한 게시글 날자별 단건 조회 API 구현
  src/main/java/cloud/emusic/emotionmusicapi/controller/PostController.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/PostRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
Labels: 💫 Feat

#80 refactor: 로그인 유저 날짜별 게시글 단건 조회 응답 방식 수정
  src/main/java/cloud/emusic/emotionmusicapi/controller/PostController.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/PostRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
Labels: 🔨 Refactor

#84 refactor: 게시글 검색 파라미터 수정
  src/main/java/cloud/emusic/emotionmusicapi/controller/PostController.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/PostRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
Labels: 🔨 Refactor

#89 refactor: post 관련 주석 작성 및 패키지 구조 변경
  src/main/java/cloud/emusic/emotionmusicapi/config/SecurityConfig.java
  src/main/java/cloud/emusic/emotionmusicapi/config/jwt/JwtAuthenticationFilter.java
  src/main/java/cloud/emusic/emotionmusicapi/config/jwt/JwtTokenProvider.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/CommentController.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/LikeController.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/LoginController.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/PostController.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/SpotifyController.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/TagController.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/UserController.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/comment/Comment.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/post/Post.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/post/PostLike.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/song/Song.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/tag/DayTag.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/tag/EmotionTag.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/tag/PostEmotionTag.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/user/Role.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/user/User.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/comment/CommentResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/login/KakaoTokenResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/login/KakaoUserResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/login/LoginResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/post/PostCreateResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/post/PostResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/song/TrackResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/song/TrackUsageResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/tag/EmotionTagResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/tag/EmotionTrackGroupResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/tag/TagRankingResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/tag/TagRankingResponseWrapper.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/user/UserInfoResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/CommentRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/DayTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/EmotionTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/LikeRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/PostEmotionTagRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/PostRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/SongRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/repository/UserRepository.java
  src/main/java/cloud/emusic/emotionmusicapi/service/CommentService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/LikeService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/PostService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/SpotifyService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/TagService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/UserService.java
Labels: 🔨 Refactor

#91 feat: JWT 토큰 유효시간 단축 및 차단 유저 처리
  src/main/java/cloud/emusic/emotionmusicapi/config/jwt/JwtTokenProvider.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/user/User.java
  src/main/java/cloud/emusic/emotionmusicapi/domain/user/UserStatus.java
  src/main/java/cloud/emusic/emotionmusicapi/exception/dto/ErrorCode.java
  src/main/java/cloud/emusic/emotionmusicapi/service/UserService.java
Labels: 💫 Feat

#101 feat: 스포티파이 Access Token 발급 API 구현 및 콜백 URL 생성 로직 리팩토링
  src/main/java/cloud/emusic/emotionmusicapi/controller/LoginController.java
  src/main/java/cloud/emusic/emotionmusicapi/dto/response/login/SpotifyTokenResponse.java
  src/main/java/cloud/emusic/emotionmusicapi/exception/dto/ErrorCode.java
  src/main/java/cloud/emusic/emotionmusicapi/service/UserService.java
Labels: 💫 Feat, 🔨 Refactor

#103 refactor: Spotify Access 토큰 발급 CSRF 방지 state 인증 로직 삭제
  src/main/java/cloud/emusic/emotionmusicapi/controller/LoginController.java
Labels: 🔨 Refactor

#115 chore: 들여쓰기 및 "-" 삭제
  compose.yaml
Labels: 🔧 Chore

#119 chore: 운영 서버의 모니터링을 위한 쿼리문 로그 출력 비활성화
  src/main/resources/application-prod.properties
Labels: 🔧 Chore

#121 Refactor: 전체적인 비즈니스 로직 트랜잭션 적용 및 controller 클래스 리팩토링
  src/main/java/cloud/emusic/emotionmusicapi/config/SecurityConfig.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/LikeController.java
  src/main/java/cloud/emusic/emotionmusicapi/controller/SpotifyController.java
  src/main/java/cloud/emusic/emotionmusicapi/service/LikeService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/SpotifyService.java
  src/main/java/cloud/emusic/emotionmusicapi/service/TagService.java
Labels: 🔨 Refactor
